### ISSUE TITLE
Implement CLHEP-compatible expression evaluator for full GDML compatibility

### ISSUE THREAD

**Issue by altavir** [mipt-npm/gdml.kt#12]
The reference for evaluator is here: http://www.apc.univ-paris7.fr/~franco/g4doxy4.10/html/class_hep_tool_1_1_evaluator.html

**Comment by Shimuuar** [comment]
I took a look at GEANT's implementation: http://www.apc.univ-paris7.fr/~franco/g4doxy4.10/html/_evaluator_8cc_source.html#l00342

- Tokenization is done manually (L426-482). Common approach is to use regexps. 
- No grammar is provided. There're generated tables (L367-461) but no mention of grammar from which they were produced. Proabaly it's better to just reuse them for compatibility
- No AST is built. Expression is evaluated immediately
- All evaluation is done using doubles 

Overall code looks as straightforward as code written in such style could be.

**Comment by altavir** [comment]
What do you want, it is done 20 years ago...
Currently, I do not require AST-based processing, simple string substitution would be enough. Good for students.

**Comment by Shimuuar** [comment]
Didn't mean that as criticism. I was fully prepared to see worse. Only real problem is absence of grammar.

I don't quite understand what do you mean by string substitution? Even after all variables are substituted you still have expressions like `1+(3*4)` which you need to evaluate. In any case I think that implementing full parser is suitable project for student. Language is simple so is evaluator.

**Comment by Shimuuar** [comment]
I made a simple tool for evaluating expression which could be used to check compatibility of any implementation: https://gist.github.com/Shimuuar/207243c4dbd72a1bbf609124984a1418

Instructions:
```
$ nix-shell 
$ make
```

**Comment by altavir** [comment]
Fixed with better-parse parser.
